version: '3.1'

services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    volumes:
      - ./policies:/policies
    command: "run --server --log-level debug --log-format=json-pretty /policies"
