EXCEL_REPORTING = "excel-reporting"
REALTIME_NOTIFICATIONS = "realtime-notifications"
EMAIL_NOTIFICATIONS = "email-notifications"

SUBSCRIPTIONS = (EMAIL_NOTIFICATIONS, REALTIME_NOTIFICATIONS, EMAIL_NOTIFICATIONS)
